## Basic Operations with Numpy

- [x] Arithmetic Operators
- [x] Matrix Product
- [x] Increment and Decrement Operators
- [x] Universal Functions
- [x] Aggregate Functions

### Arithmetic Operators

In [48]:
import numpy as np
a = np.arange(4)

# addition
a + 4

array([4, 5, 6, 7])

In [49]:
# multiplication
a * 2

array([0, 2, 4, 6])

In [50]:
b = np.arange(4,8)

# adding two numpy arrays
a + b

array([ 4,  6,  8, 10])

In [51]:
# subtracting two numpy arrays
a - b

array([-4, -4, -4, -4])

In [52]:
# multiplying two numpy arrays
a * b

array([ 0,  5, 12, 21])

In [53]:
# operators with numpy functions
a * np.sin(b)

array([-0.        , -0.95892427, -0.558831  ,  1.9709598 ])

In [54]:
a * np.sqrt(b)

array([0.        , 2.23606798, 4.89897949, 7.93725393])

In [55]:
# operators on multidimensional arrays
A = np.arange(0, 9).reshape(3, 3)
B = np.ones((3, 3))

A * B

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

### Matrix Product

In [56]:
# matrix product (not element wise)
np.dot(A,B)

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])

In [57]:
# alternative matrix product
A.dot(B)

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])

### Increment and Decrement Operators

In [58]:
a = np.arange(4)

# increment by one
a += 1
a

array([1, 2, 3, 4])

In [59]:
# decrement by one
a -= 1
a

array([0, 1, 2, 3])

In [60]:
# increment by 4
a += 4
a

array([4, 5, 6, 7])

### Universal Functions
Universal Functions operate on any given numpy array in element-by-element fashion thereby generating a corresponding result for each element in the array

In [61]:
# square root function
a = np.arange(1,5)

np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [62]:
# logarithm function
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [63]:
# sine function
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

### Aggregate Functions
Aggregate Functions perform an operation on a set of values to produce a single result

In [64]:
a = np.array([3.3, 4.5, 1.2, 5.7, 0.3])

# sum function
print(a.sum())

15.0


In [65]:
# min function
a.min()

0.3

In [66]:
# max function
a.max()

5.7

In [67]:
# mean function
a.mean()

3.0

In [68]:
# standard deviation function
a.std()

2.0079840636817816