## Indexing, Slicing and Iterating
 - [x] Indexing
 - [x] Slicing
 - [x] Iterating

### Indexing

In [1]:
import numpy as np 

a = np.arange(10,16)

In [2]:
# selection by index
a[4]

14

In [3]:
# selection by negative index
a[-1]

a[-6]

15

In [4]:
# multiple selection
a[[1, 3, 4]]

array([11, 13, 14])

In [5]:
A = np.arange(10, 19).reshape((3, 3))

# indexing matrices (two dimentional arrays)
A[1, 2]

15

### Slicing

In [6]:
a = np.arange(10, 16)

# slicing numpy array
a[1:5]

array([11, 12, 13, 14])

In [7]:
# slicing with intervals
a[1:5:2]

array([11, 13])

In [8]:
# omitting start index for slice
a[:5:2]

array([10, 12, 14])

In [9]:
# omitting ending index for slice
a[1::2]

array([11, 13, 15])

In [10]:
# including only interval value for slice
a[::2]

array([10, 12, 14])

In [12]:
# slicing a matrix
A = np.arange(10, 19).reshape((3, 3))

# slicing first row
A[0, :]

array([10, 11, 12])

In [13]:
# slicing first column
A[:, 0]

array([10, 13, 16])

In [14]:
# extracting a smaller matrix
A[0:2, 0:2]

array([[10, 11],
       [13, 14]])

### Iterating

In [15]:
a = np.arange(10, 16)

# iterating an array
for i in a:
    print(i)


10
11
12
13
14
15


In [17]:
A = np.arange(10, 19).reshape((3, 3))

# iterating a matrix
for row in A:
    print(row)

[10 11 12]
[13 14 15]
[16 17 18]


In [18]:
# iterating matrix by element
for item in A.flat:
    print(item)

10
11
12
13
14
15
16
17
18


Numpy can iterate and perform operations on matrices with the `apply_along_axis` function. The function takes three arguments: an aggregate function, axis direction, and matrix to operate on

In [19]:
np.apply_along_axis(np.mean, axis=0, arr=A) # when axis=0, direction is column

array([13., 14., 15.])

In [20]:
np.apply_along_axis(np.mean, axis=1, arr=A) #when axis=1, direction is row

array([11., 14., 17.])

In [21]:
# using custom function

def dev_by_2(x):
    return x/2

np.apply_along_axis(dev_by_2, axis=1, arr=A)

array([[5. , 5.5, 6. ],
       [6.5, 7. , 7.5],
       [8. , 8.5, 9. ]])

In [22]:
np.apply_along_axis(dev_by_2, axis=0, arr=A)

array([[5. , 5.5, 6. ],
       [6.5, 7. , 7.5],
       [8. , 8.5, 9. ]])