## Conditions and Boolean Arrays

In [1]:
import numpy as np 

A = np.random.random((4, 4))
A

array([[0.10897207, 0.87422807, 0.83247242, 0.18243146],
       [0.91267246, 0.18520466, 0.71986893, 0.53037079],
       [0.83771726, 0.56629875, 0.20765026, 0.14147216],
       [0.45384461, 0.35555568, 0.69360351, 0.52832303]])

In [2]:
# condition operator
A < 0.5

array([[ True, False, False,  True],
       [False,  True, False, False],
       [False, False,  True,  True],
       [ True,  True, False, False]])

In [3]:
# extracting values based on condition
A[A < 0.5]

array([0.10897207, 0.18243146, 0.18520466, 0.20765026, 0.14147216,
       0.45384461, 0.35555568])