## Shape Manipulation

In [2]:
import numpy as np

a = np.random.random(12)

a

array([0.00985922, 0.38026697, 0.79048169, 0.92000031, 0.10520014,
       0.05785142, 0.37474571, 0.59019408, 0.07082724, 0.31197299,
       0.90340699, 0.13954121])

In [4]:
A = a.reshape(3, 4)
A

array([[0.00985922, 0.38026697, 0.79048169, 0.92000031],
       [0.10520014, 0.05785142, 0.37474571, 0.59019408],
       [0.07082724, 0.31197299, 0.90340699, 0.13954121]])

In [6]:
# modify shape of an array
a.shape = (3, 4)

a

array([[0.00985922, 0.38026697, 0.79048169, 0.92000031],
       [0.10520014, 0.05785142, 0.37474571, 0.59019408],
       [0.07082724, 0.31197299, 0.90340699, 0.13954121]])

In [8]:
# convert matrix to array
a.ravel()

array([0.00985922, 0.38026697, 0.79048169, 0.92000031, 0.10520014,
       0.05785142, 0.37474571, 0.59019408, 0.07082724, 0.31197299,
       0.90340699, 0.13954121])

In [9]:
# transpose a matrix
A.transpose()

array([[0.00985922, 0.10520014, 0.07082724],
       [0.38026697, 0.05785142, 0.31197299],
       [0.79048169, 0.37474571, 0.90340699],
       [0.92000031, 0.59019408, 0.13954121]])