## Array Manipulation

- [ ] Joining Arrays
- [ ] Splitting Arrays

### Joining Arrays

In [2]:
import numpy as np

A = np.ones((3, 3))
B = np.zeros((3, 3))

# vertical stacking 
np.vstack((A, B))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [3]:
# horizontal stacking
np.hstack((A, B))

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

In [4]:
a = np.array([0, 1, 2])
b = np.array([3, 4, 5])
c = np.array([6, 7, 8])

# column stack
np.column_stack((a, b, c))

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [5]:
# row stack
np.row_stack((a, b, c))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### Splitting Arrays

In [6]:
A = np.arange(16).reshape((4, 4))
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [7]:
# horizontal split
[B, C] = np.hsplit(A, 2)

B 
C

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [9]:
# vertical split
[B, C] = np.vsplit(A, 2)

B
C

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [14]:
# It is possible to split an array into nonsymmetrical parts. This is done by specifying the indexes of the parts to be divided. 
#
# For example, in order to split a matrix into three parts:
#   array([[ 0,  1,  2,  3],
#          [ 4,  5,  6,  7],
#          [ 8,  9, 10, 11],
#          [12, 13, 14, 15]])


[A1, A2, A3] = np.split(A, [1, 3], axis=1) # axis=1 (column)

A1
A2
A3

array([[ 3],
       [ 7],
       [11],
       [15]])

In [18]:
[A1, A2, A3] = np.split(A, [1, 3], axis=0) # axis=0 (row)

A1
A2
A3

array([[12, 13, 14, 15]])